name: Compilar APK con Buildozer

on:
  push:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout del código
        uses: actions/checkout@v4

      - name: Construir APK con Buildozer Action
        uses: ArtemSBulgakov/buildozer-action@v1
        id: buildozer
        with:
          command: android debug
          buildozer_version: master

      - name: Subir el APK como artefacto
        uses: actions/upload-artifact@v4
        with:
          name: app-debug-apk
          path: bin/*.apk
